app:
  security:
    dev-user:
      enabled: true
      username: admin@interviewos.local
      password: admin123
      roles:
        - ADMIN
spring:
  application:
    name: ostip
  datasource:
    url: jdbc:postgresql://localhost:5432/interviewos
    username: interviewos
    password: interviewos

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration