app:
  security:
    dev-user:
      enabled: true
      username: admin@interviewos.local
      password: admin123
      roles:
        - ADMIN
interviewos:
  cache:
    ttl:
      candidates: 30m
      interview-templates: 1h
      organizations: 6h
      organization-settings: 12h
      email-verification: 15m
      password-reset: 10m
      login-attempts: 30m
spring:
  profiles:
    active: dev
  application:
    name: ostip
  datasource:
    url: jdbc:postgresql://localhost:5432/interviewos
    username: interviewos
    password: interviewos

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration